# https://kind.sigs.k8s.io/docs/user/configuration/
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

# https://kind.sigs.k8s.io/docs/user/configuration/#name-your-cluster
name: <replace>

nodes:
- role: control-plane
  image: <replace>
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    listenAddress: <replace>
  - containerPort: 2379
    hostPort: 2379
    listenAddress: <replace>
  - containerPort: 2380
    hostPort: 2380
    listenAddress: <replace>
  - containerPort: 10250
    hostPort: 10250
    listenAddress: <replace>
  extraMounts:
  - hostPath: <replace>
    containerPath: <replace>
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs: [
        <replace>
      ]

- role: worker  
  image: <replace>
  extraMounts:
  - hostPath: <replace>
    containerPath: <replace>

networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true